// Mimo pronto: estoque intermediário produzido a partir de uma receita editável.
function mimoEnsure(){db.settings=db.settings||{};if(!Array.isArray(db.settings.mimoRecipe)||!db.settings.mimoRecipe.length){let find=re=>db.stock.find(s=>re.test(`${s.type||''} ${s.customType||''} ${s.cat||''} ${s.name||''}`)),a=[],card=find(/cart[aã]o.*p[oó]s/i),pot=find(/potinho/i);if(card)a.push({stockId:card.id,qty:1});if(pot)a.push({stockId:pot.id,qty:1});db.settings.mimoRecipe=a}if(!db.stock.some(s=>s.isMimoReady))db.stock.push({id:uid(),name:'Mimo pronto',cat:'Mimo pronto',type:'Mimo pronto',customType:'Mimo pronto',unit:'un',qty:0,min:0,cost:0,isMimoReady:true});return db.stock.find(s=>s.isMimoReady)}
function mimoStock(){return mimoEnsure()}
function mimoRecipeRows(){mimoEnsure();return(db.settings.mimoRecipe||[]).map((m,i)=>{let s=db.stock.find(x=>String(x.id)===String(m.stockId));return s?`<div class="row item"><div style="flex:1"><b>${esc(s.name)}</b><div class="tiny">${esc(s.unit||'un')} por mimo</div></div><input data-mimoq="${i}" type="number" min="0" step=".01" value="${m.qty}" style="width:76px"><button type="button" class="btn light" onclick="mimoRemoveRecipe(${i})">✕</button></div>`:''}).join('')}
function mimoView(){let m=mimoEnsure();form('Mimo pronto',`<div class="card"><div class="row"><span>Prontos em estoque</span><b>${fmt(m.qty)} un</b></div></div><button type="button" class="btn light full" id="mimoExisting">+ Já tenho mimos prontos</button><h2>Composição</h2>${mimoRecipeRows()}<button type="button" class="btn light full" id="mimoAdd">+ Adicionar insumo</button><h2>Produzir</h2><label>Quantidade de mimos que preparei</label><input id="mimoMakeQty" type="number" min="1" step="1" value="1">`,mimoProduce,'Produzir mimos');$('#mimoAdd').onclick=mimoAddPicker;$('#mimoExisting').onclick=mimoAddExisting}
function mimoAddExisting(){form('Mimos que já tenho',`<div class="tiny">Adiciona mimos já preparados sem descontar nenhum insumo.</div><label>Quantidade pronta</label><input id="mimoExistingQty" type="number" min="1" step="1">`,()=>{let n=Math.floor(+$('#mimoExistingQty').value||0);if(n<=0){alert('Informe a quantidade pronta.');return}let m=mimoStock();m.qty=(+m.qty||0)+n;db.moves.push({id:uid(),stockId:m.id,qty:n,type:'estoque-inicial-mimo',date:new Date().toISOString()});save();mimoView()},'Adicionar')}
function mimoSaveRecipeInputs(){document.querySelectorAll('[data-mimoq]').forEach(i=>{let x=db.settings.mimoRecipe[+i.dataset.mimoq];if(x)x.qty=Math.max(0,+i.value||0)})}
function mimoAddPicker(){mimoSaveRecipeInputs();let used=new Set((db.settings.mimoRecipe||[]).map(x=>String(x.stockId))),opts=db.stock.filter(s=>!s.isMimoReady&&!used.has(String(s.id))).map(s=>`<option value="${s.id}">${esc(s.name)} · ${fmt(s.qty)} ${esc(s.unit||'un')}</option>`).join('');form('Adicionar ao mimo',opts?`<label>Insumo</label><select id="mimoAddStock">${opts}</select><label>Quantidade por mimo</label><input id="mimoAddQty" type="number" min=".01" step=".01" value="1">`:empty('Todos os insumos já foram adicionados.'),()=>{if(!opts)return mimoView();let id=$('#mimoAddStock').value,q=+$('#mimoAddQty').value||0;if(q>0)db.settings.mimoRecipe.push({stockId:isNaN(+id)?id:+id,qty:q});save();mimoView()},'Adicionar')}
function mimoRemoveRecipe(i){mimoSaveRecipeInputs();db.settings.mimoRecipe.splice(i,1);save();mimoView()}
function mimoProduce(){mimoSaveRecipeInputs();let n=Math.floor(+$('#mimoMakeQty').value||0);if(n<=0){alert('Informe quantos mimos foram preparados.');return}let recipe=(db.settings.mimoRecipe||[]).filter(x=>+x.qty>0);if(!recipe.length){alert('Configure a composição do mimo.');return}for(let x of recipe){let s=db.stock.find(a=>String(a.id)===String(x.stockId)),need=(+x.qty||0)*n;if(!s||need>(+s.qty||0)){alert(`Estoque insuficiente para ${s?.name||'insumo'}.`);return}}let total=0;for(let x of recipe){let s=db.stock.find(a=>String(a.id)===String(x.stockId)),need=(+x.qty||0)*n;s.qty-=need;total+=need*(+s.cost||0);db.moves.push({id:uid(),stockId:s.id,qty:-need,type:'producao-mimo',date:new Date().toISOString()})}let m=mimoStock(),old=+m.qty||0,oldVal=old*(+m.cost||0);m.qty=old+n;m.cost=(oldVal+total)/(old+n);db.moves.push({id:uid(),stockId:m.id,qty:n,type:'producao-mimo',date:new Date().toISOString()});save();closeM();render()}
function mimoMaterial(qty=1){let m=mimoStock();return m?[{stockId:m.id,qty}]:[]}
