// V11 - Nova Flash Tattoo compacta + mimo padrão
function flashDefaultKitItems(){return [
 {type:'Gilete',qty:1},{type:'Luvas',qty:1},{type:'Papel de limpeza',qty:4},{type:'Papel vegetal',qty:1},
 {type:'Plástico filme P',qty:1},{type:'Bandagem',qty:1},{type:'Fita',qty:1},{type:'Palito / espátula',qty:1},
 {type:'Cuidados pós',qty:1},{type:'Potinho 4g',qty:1},{type:'Pomada cicatrizante',qty:3}
]}
function ensureFlashKitV11(){let kit=db.kits.find(k=>k.key==='flash-evento');if(!kit){kit={id:uid(),key:'flash-evento',name:'Kit Flash Evento',items:[]};db.kits.push(kit)}let desired=flashDefaultKitItems();desired.forEach(d=>{let found=kit.items.find(i=>i.type===d.type);if(found)found.qty=d.qty;else kit.items.push({...d})});kit.items=kit.items.filter(i=>i.type!=='Máscara'&&i.type!=='Pomada mimo');save()}
ensureFlashKitV11();
function flashDetailsToggle(){let el=$('#flashDetails'),b=$('#flashDetailsBtn');if(!el)return;let open=el.style.display!=='none';el.style.display=open?'none':'block';if(b)b.textContent=open?'Observações / detalhes ▾':'Ocultar detalhes ▴'}
function addSelectedFlashMaterial(){let sel=$('#mi'),q=$('#mq');if(!sel||!sel.value)return;let x=db.stock.find(s=>s.id==sel.value);if(!x||x.qty<=0)return;let existing=draft.find(d=>d.stockId===x.id&&!d.auto);if(existing)existing.qty=1;else draft.push({stockId:x.id,name:x.name,qty:1,unit:x.unit,cost:x.cost});q.value=1;draftList()}
function flashForm(old,eventId){if(!eventId){alert('A Flash Tattoo deve ser registrada dentro de um evento.');return}draft=old?(old.materials||[]).filter(x=>!x.auto).map(x=>({...x})):[];let e=db.events.find(x=>x.id===eventId);form(old?'Editar Flash Tattoo':'Nova Flash Tattoo',`<div class="pill">Evento: ${e?.name||'Evento'}</div><label>@ Instagram</label><input id="tn" value="${old?.instagram||old?.name||''}" placeholder="@usuario" autocapitalize="none"><div class="grid"><div><label>Tempo</label><input id="tduration" type="time" step="60" value="${minutesToDuration(old?.duration||15)}"></div><div><label>Valor</label><input id="tp" type="number" step=".01" value="${old?.price??120}"></div></div><h2>Materiais</h2><div class="card"><b>Kit Flash Evento</b><div class="tiny">Aplicado ao salvar: consumíveis padrão + cartão pós-tattoo + 1 potinho + 3 g de pomada + Vitalderm.</div></div><label>Cor principal</label><select id="fcolor" onchange="flashInkFields()"><option ${old?.inkColor!=='Vermelha'?'selected':''}>Preta</option><option ${old?.inkColor==='Vermelha'?'selected':''}>Vermelha</option></select><label class="row" style="justify-content:flex-start"><input id="fwhite" type="checkbox" style="width:auto;margin:0" ${old?.whiteDetail?'checked':''} onchange="flashInkFields()"> Detalhe branco</label><div id="inkStatus" class="card tiny"></div><label>Cartucho</label><div class="row"><select id="mi" style="flex:1">${materialOptions()}</select><div style="width:92px"><input id="mq" type="number" value="1" min="1" max="1" readonly></div><button class="btn light" type="button" onclick="addSelectedFlashMaterial()">+ Adicionar</button></div><div class="tiny">1 unidade por modelo. Para usar outro modelo, selecione e adicione.</div><div id="draftList"></div><button class="btn light full" type="button" onclick="flashDetailsToggle()" id="flashDetailsBtn">Observações / detalhes ▾</button><div id="flashDetails" style="display:none"><div class="grid"><div><label>Tamanho (cm)</label><input id="tsize" type="number" step=".1" value="${old?.size||5}"></div><div><label>Complexidade</label><select id="tcomplex"><option ${!old||old?.complexity==='Baixa'?'selected':''}>Baixa</option><option ${old?.complexity==='Média'?'selected':''}>Média</option><option ${old?.complexity==='Alta'?'selected':''}>Alta</option></select></div></div><label>Local do corpo</label><select id="tbody">${bodyOptions(old?.bodyPlace)}</select><label>Observações</label><textarea id="tnotes" rows="3" placeholder="Opcional">${old?.notes||''}</textarea></div><input id="td" type="hidden" value="${old?.isoDate||e?.date||new Date().toISOString().slice(0,10)}">`,()=>saveEventFlashV11(old,eventId),old?'SALVAR ALTERAÇÕES':'SALVAR FLASH TATTOO');setTimeout(()=>{draftList();flashInkFields()},0)}
function saveEventFlashV11(old,eventId){let size=+($('#tsize')?.value||old?.size||5),complexity=$('#tcomplex')?.value||old?.complexity||'Baixa',body=$('#tbody')?.value||old?.bodyPlace||'Braço',notes=$('#tnotes')?.value||old?.notes||'';if(old)restoreMaterials(old);else{applyFlashKit();addFlashInkConsumption();addVitaldermBySize(size);ensureEventMask(eventId)}let t=old||{id:uid()};t.name=$('#tn').value||'Flash';t.instagram=t.name;t.client='';t.size=size;t.complexity=complexity;t.bodyPlace=body;t.notes=notes;t.duration=durationToMinutes($('#tduration').value);t.price=+$('#tp'].value||120;t.received=t.price;t.remaining=0;t.paymentStatus='Pago';t.isoDate=$('#td'].value;t.date=new Date(t.isoDate+'T12:00').toLocaleDateString('pt-BR');t.inkColor=$('#fcolor'].value;t.whiteDetail=$('#fwhite'].checked;t.materials=draft.map(x=>({...x}));t.cost=t.materials.reduce((s,m)=>s+(+m.cost||0)*(+m.qty||0),0);t.eventId=eventId;t.kind='flash';consumeMaterials(t);if(!old)db.tattoos.push(t);save();closeM();eventSheet(eventId)}
