// V8 - Kit Flash Evento, consumo automático e manutenção em massa do estoque
if(!db.kits)db.kits=[];
const flashKitDefaults=[
 {type:'Gilete',qty:1},{type:'Luvas',qty:1},{type:'Papel de limpeza',qty:4},{type:'Papel vegetal',qty:1},
 {type:'Plástico filme P',qty:1},{type:'Bandagem',qty:1},{type:'Fita',qty:1},{type:'Palito / espátula',qty:1},
 {type:'Máscara',qty:0},{type:'Cuidados pós',qty:1},{type:'Pomada mimo',qty:1}
];
function stockByType(type){return db.stock.find(x=>x.type===type||x.name===type||x.name?.toLowerCase().includes(type.toLowerCase()))}
function ensureFlashKit(){if(!db.kits.find(k=>k.key==='flash-evento'))db.kits.push({id:uid(),key:'flash-evento',name:'Kit Flash Evento',items:flashKitDefaults});save()}
ensureFlashKit();
function applyFlashKit(){let kit=db.kits.find(k=>k.key==='flash-evento'),missing=[];(kit?.items||[]).forEach(i=>{if(!i.qty)return;let x=stockByType(i.type);if(x&&x.qty>=i.qty)draft.push({stockId:x.id,name:x.name,qty:i.qty,unit:x.unit,cost:x.cost,auto:true});else missing.push(i.type)});draftList();let el=$('#kitStatus');if(el)el.innerHTML=`Kit aplicado ✓${missing.length?`<div class="tiny">Sem estoque cadastrado: ${missing.join(', ')}</div>`:''}`}
function flashInkFields(){let color=$('#fcolor')?.value,white=$('#fwhite')?.checked,el=$('#inkStatus');if(el)el.innerHTML=`Cor principal: <b>${color}</b>${white?' · detalhe branco + copinho com água':''}`}
function addFlashInkConsumption(){let color=$('#fcolor').value,white=$('#fwhite').checked,batoque=db.stock.find(x=>x.cat==='Batoques'&&(x.model==='P'||x.name.includes('P'))),ink=db.stock.find(x=>x.cat==='Tintas'&&x.name.toLowerCase().includes(color==='Preta'?'black':color==='Vermelha'?'verm':'branc'))||db.stock.find(x=>x.cat==='Tintas'&&x.name.toLowerCase().includes(color.toLowerCase()));if(batoque&&batoque.qty>0)draft.push({stockId:batoque.id,name:batoque.name,qty:1,unit:batoque.unit,cost:batoque.cost,auto:true});if(ink){let ml=+(batoque?.capacityMl||batoque?.ml||1);draft.push({stockId:ink.id,name:ink.name,qty:ml,unit:'ml',cost:ink.cost,auto:true})}if(white){let w=db.stock.find(x=>x.cat==='Tintas'&&(x.name.toLowerCase().includes('white')||x.name.toLowerCase().includes('branc')));if(w){let ml=+(batoque?.capacityMl||batoque?.ml||1);draft.push({stockId:w.id,name:w.name,qty:ml,unit:'ml',cost:w.cost,auto:true})}let cup=stockByType('Copo descartável');if(cup)draft.push({stockId:cup.id,name:cup.name,qty:1,unit:cup.unit,cost:cup.cost,auto:true})}}
function addVitaldermBySize(size){let v=db.stock.find(x=>x.type==='Vitalderm'||x.name.toLowerCase().includes('vitalderm'));if(v&&size>0)draft.push({stockId:v.id,name:v.name,qty:size,unit:v.unit,cost:v.cost,auto:true})}
function flashForm(old,eventId){draft=old?(old.materials||[]).filter(x=>!x.auto).map(x=>({...x})):[];form(old?'Editar flash':'Nova flash rápida',`<label>@ Instagram</label><input id="tn" value="${old?.instagram||old?.name||''}" placeholder="@usuario" autocapitalize="none"><div class="grid"><div><label>Tamanho (cm)</label><input id="tsize" type="number" step=".1" value="${old?.size||5}"></div><div><label>Complexidade</label><select id="tcomplex"><option ${!old||old?.complexity==='Baixa'?'selected':''}>Baixa</option><option ${old?.complexity==='Média'?'selected':''}>Média</option><option ${old?.complexity==='Alta'?'selected':''}>Alta</option></select></div></div><label>Local do corpo</label><select id="tbody">${bodyOptions(old?.bodyPlace)}</select><label>Tempo</label><input id="tduration" type="time" step="60" value="${minutesToDuration(old?.duration)}"><label>Valor</label><input id="tp" type="number" step=".01" value="${old?.price??120}" oninput="flashPaidDefault()"><label>Recebido</label><input id="tsignal" type="number" step=".01" value="${old?.received??old?.price??120}"><h2>Kit Flash Evento</h2><div class="card"><div class="row"><b>Kit padrão</b><button class="btn light" type="button" onclick="applyFlashKit()">Aplicar kit</button></div><div id="kitStatus" class="tiny">Aplica automaticamente os consumíveis padrão.</div></div><label>Cor principal</label><select id="fcolor" onchange="flashInkFields()"><option>Preta</option><option>Vermelha</option></select><label class="row" style="justify-content:flex-start"><input id="fwhite" type="checkbox" style="width:auto;margin:0" onchange="flashInkFields()"> Detalhe branco</label><div id="inkStatus" class="card tiny"></div><label>Cartucho</label><select id="mi">${materialOptions()}</select><button class="btn light full" type="button" onclick="$('#mq').value=1;addDraft()">+ Adicionar cartucho/material</button><input id="mq" type="hidden" value="1"><div id="draftList"></div><label>Observações</label><textarea id="tnotes" rows="3" placeholder="Opcional">${old?.notes||''}</textarea><input id="td" type="hidden" value="${old?.isoDate||new Date().toISOString().slice(0,10)}">`,()=>{if(!old){applyFlashKit();addFlashInkConsumption();addVitaldermBySize(+$('#tsize').value||5)}saveTattooV7(old,eventId,true)},old?'SALVAR ALTERAÇÕES':'SALVAR FLASH');setTimeout(()=>{draftList();flashInkFields()},0)}
function editFlashKit(){let kit=db.kits.find(k=>k.key==='flash-evento');form('Editar Kit Flash Evento',`<div class="card tiny">Defina o consumo automático de cada flash. Zero = não incluir.</div>${kit.items.map((i,n)=>`<div class="row"><span>${i.type}</span><input id="k${n}" type="number" step=".01" value="${i.qty}" style="width:90px"></div>`).join('')}`,()=>{kit.items.forEach((i,n)=>i.qty=+$('#k'+n).value||0);save();closeM()},'SALVAR KIT')}
function bulkStockEdit(){form('Editar estoque',`<div class="card tiny">Edite vários itens e salve tudo de uma vez.</div>${db.stock.map(x=>`<div class="card" id="bs${x.id}"><b>${x.name}</b><div class="grid"><div><label>Quantidade</label><input id="bq${x.id}" type="number" step=".01" value="${x.qty}"></div><div><label>Estoque mínimo</label><input id="bm${x.id}" type="number" step=".01" value="${x.min||0}"></div></div><button class="btn light full" type="button" onclick="if(confirm('Excluir ${x.name.replace(/'/g,"\\'")}?')){this.closest('.card').dataset.delete='1';this.closest('.card').style.opacity='.35'}">Marcar para excluir</button></div>`).join('')}`,()=>{db.stock=[...db.stock].filter(x=>{let row=$('#bs'+x.id);if(row?.dataset.delete==='1')return false;x.qty=Math.max(0,+$('#bq'+x.id).value||0);x.min=Math.max(0,+$('#bm'+x.id).value||0);return true});save();closeM();render()},'SALVAR ALTERAÇÕES')}
function stock(){let list=shoppingList();return `<div class="brand">Estoque</div><button class="btn full" onclick="stockEntry()">+ Adicionar compra / material</button><div class="grid" style="margin-top:10px"><button class="btn light" onclick="bulkStockEdit()">Editar estoque</button><button class="btn light" onclick="editFlashKit()">Kit Flash Evento</button><button class="btn light" onclick="purchaseHistory()">Itens comprados</button><button class="btn light" onclick="shoppingListView()">Lista de compras${list.length?' ('+list.length+')':''}</button></div><h2>Inventário</h2>${db.stock.map(x=>`<div class="card" onclick="editStock(${x.id})"><div class="row"><div><b>${x.name}</b><div class="tiny">${x.cat} · ${money(x.cost)}/${x.unit}</div></div><b class="${x.qty<=x.min?'red':''}">${fmtQty(x.qty)} ${x.unit}</b></div><div class="tiny">Toque para editar/excluir · mínimo ${fmtQty(x.min||0)} ${x.unit}</div></div>`).join('')}`}
